# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 73f86789a51437c1199cca74f01316d3e8d938b00ab3d6546e0eef4c6522acb70a3cd2f8898e77eec598178e3e29fa2b25ff56d26d12a54203cd372fdb01f383

test:
  secret_key_base: 9e0c4866c19c0d4557e589430c26dd0c30db7703a04ed19c920cd43da2ffa21767258ba67e747a8ed712448d8f05264fd9a73b1cd31a55dfa6957016a7412f0f

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
